d /run/remydesk 0755 remydesk remydesk -
d /var/lib/remydesk 0750 remydesk remydesk -
d /srv/remydesk 0755 remydesk remydesk -
d /srv/remydesk/data 0750 remydesk remydesk -
L+ /dev/dma_heap/system-uncached - - - - /dev/dma_heap/system
L+ /dev/dma_heap/cma-uncached - - - - /dev/dma_heap/system
L+ /dev/dma_heap/system-uncached-dma32 - - - - /dev/dma_heap/system
